/*
 * This file is part of Baritone.
 *
 * Baritone is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Baritone is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Baritone. If not, see <https://www.gnu.org/licenses/>.
 */

package baritone.command.defaults;

import baritone.api.IBaritone;
import baritone.api.command.Command;
import baritone.api.command.argument.IArgConsumer;
import baritone.api.command.exception.CommandException;
import baritone.api.command.exception.CommandInvalidStateException;
import baritone.auth.Authorization;
import baritone.auth.LicenseValidator;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

/**
 * One-time license activation command.
 *
 * <p>Usage: {@code #activate <token>}
 *
 * <p>The token is generated by the mod owner with {@code generate_license.ps1}.
 * On success the token is saved to {@code baritone/license.key} and the
 * authorization cache is reset so the next command goes through normally.
 *
 * <p>This command is intentionally exempt from the authorization check in
 * {@code CommandManager} so that unlicensed players can activate.
 */
public class ActivateCommand extends Command {

    public ActivateCommand(IBaritone baritone) {
        super(baritone, "activate", "license");
    }

    @Override
    public void execute(String label, IArgConsumer args) throws CommandException {
        args.requireMin(1);
        args.requireMax(1);
        String token = args.getString();

        LicenseValidator.Result result = LicenseValidator.validate(token);
        switch (result.status) {
            case VALID -> {
                try {
                    LicenseValidator.save(token);
                    Authorization.reset();
                    logDirect("[MinecraftAI] Activated! Licensed to: " + result.name
                            + " (expires " + result.expiry + ")");
                } catch (Exception e) {
                    throw new CommandInvalidStateException(
                            "Failed to save license file: " + e.getMessage());
                }
            }
            case EXPIRED ->
                logDirect("[MinecraftAI] Error 001. Please contact owner.");
            default ->
                logDirect("[MinecraftAI] Error 001. Please contact owner.");
        }
    }

    @Override
    public Stream<String> tabComplete(String label, IArgConsumer args) {
        return Stream.empty();
    }

    @Override
    public String getShortDesc() {
        return "Activate MinecraftAI with a license token";
    }

    @Override
    public List<String> getLongDesc() {
        return Arrays.asList(
                "Activates MinecraftAI using a license token from the mod owner.",
                "",
                "Usage:",
                "> #activate <token>",
                "",
                "The token is given to you by the mod owner. Type it once — it is",
                "saved locally and you won't need to enter it again."
        );
    }
}
